# Generated by Django 2.0.5 on 2019-02-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinememo2', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
